version: '3.8'

services:
  beanstalkd-1:
    image: schickling/beanstalkd
    container_name: beanstalkd-1
    platform: linux/amd64
    ports:
      - "11300:11300"
    volumes:
      - ./data/beanstalkd-1:/data
    environment:
      BEANSTALKD_PORT: 11300

  beanstalkd-2:
    image: schickling/beanstalkd
    container_name: beanstalkd-2
    platform: linux/amd64
    ports:
      - "11301:11300"
    volumes:
      - ./data/beanstalkd-2:/data
    environment:
      BEANSTALKD_PORT: 11300

  beanstalkd-3:
    image: schickling/beanstalkd
    container_name: beanstalkd-3
    platform: linux/amd64
    ports:
      - "11302:11300"
    volumes:
      - ./data/beanstalkd-3:/data
    environment:
      BEANSTALKD_PORT: 11300

volumes:
  beanstalkd-1-data:
  beanstalkd-2-data:
  beanstalkd-3-data:
